export const GET_GALLERY_REQUEST = "GET_GALLERY_REQUEST"
export const GET_GALLERY_SUCCESS = "GET_GALLERY_SUCCESS"
export const GET_GALLERY_FAIL = "GET_GALLERY_FAIL"

export const GET_GALLERY_DETAILS_REQUEST = "GET_GALLERY_DETAILS_REQUEST"
export const GET_GALLERY_DETAILS_SUCCESS = "GET_GALLERY_DETAILS_SUCCESS"
export const GET_GALLERY_DETAILS_FAIL = "GET_GALLERY_DETAILS_FAIL"
export const GET_GALLERY_DETAILS_RESET = "GET_GALLERY_DETAILS_RESET"